# Window dimensions
MAIN_WINDOW_WIDTH = 900
MAIN_WINDOW_HEIGHT = 2000

# Section heights
BASIC_SECTION_HEIGHT = 800
ADVANCED_SECTION_HEIGHT = 350
LOG_CONTAINER_MIN_HEIGHT = 100

# Spacing
MIDDLE_SPACE = 12

# Widget specific dimensions
LOGIC_LIST_WIDTH = 345
LOGIC_DETAIL_WIDTH = 345
LOGIC_MAKER_WIDTH = 180
LOGIC_OPERATION_WIDTH = 345  # 로직 조작 영역 너비
ADVANCED_FRAME_WIDTH = 870
LOG_FRAME_WIDTH = 870

# Button dimensions
LOGIC_BUTTON_WIDTH = 280 // 4  # For logic list and detail buttons
MAKER_BUTTON_WIDTH = 160  # For logic maker buttons

# 회복 기준값
DEFAULT_RECOVERY_THRESHOLD = 25
